### PR TITLE
Reference sql from ispyb-database

### PR DESCRIPTION
**Pull request by stufisher**
Reference sql files from https://github.com/ispyb/ispyb-database

### CODE REVIEW

**Comment by stufisher** [comment]
Not yet tried to build this

**Comment by mgaonach** [comment]
Do we want the test datafiles to be in the [ispyb-database](https://github.com/ispyb/ispyb-database) repository too? They are not part of the database schema. I think they are more tied to this repository.

**Comment by stufisher** [comment]
I think its ok to keep them in the sql repo, then everything is in the same place. There is a note in `ispyb-database` telling you that this is test data and not required for production.

**Comment by mgaonach** [comment]
Maybe having this `schema` directory for the schema only, and a `data` or `development` directory then? Relying on people reading the docs does not always work :) And I think it is good to clearly separate what is for production and what is for development.

**Review by mgaonach — APPROVED** [review]

**Pull request merged**
